class LemonError(Exception):
    """Base class. Every LEMON error fails closed."""

class IntegrityError(LemonError): ...
class SelfReviewError(LemonError): ...
class SelfApprovalError(LemonError): ...
class ProviderOutputError(LemonError): ...
class ProviderError(LemonError): ...
class ScientificHoldError(LemonError): ...
class PromotionError(LemonError): ...
class LeakageError(LemonError): ...
class PathSecurityError(LemonError): ...
class PassportIncompleteError(LemonError): ...
